# Generated by Django 5.0.6 on 2024-05-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('mentor', 'Mentor'), ('judge', 'Judge'), ('workshop_leader', 'Workshop Leader')], default='mentor', max_length=20)),
                ('availabilities', models.ManyToManyField(blank=True, to='schedule.availability')),
            ],
        ),
    ]
